### ISSUE TITLE
La estructura de tu repositorio no cumple con lo solicitado

### ISSUE THREAD

**Issue by FrancoMarengo** [FernandoRoldan77/EstrD2023s1#32]
Las entregas tienen que respetar la siguiente estructura de carpetas y nombres: tp-1/tp-1.hs

**Comment by FernandoRoldan77** [comment]
Corregido, en ningún lado del campus leí algo respecto a los nombres en el campus en la parte de git, solo lo referido al nombre de EstrD2023s1, agregar colaboradores y nuestro nombre y Apellido, por las dudas aclaro , si estaba en otro recurso esa información te pido disculpas.

**Comment by FrancoMarengo** [comment]
Perfecto Fernando. No, este año no aparece en ningún lado esa pauta, es más que nada un issue para recomendarte una estructura y mantenerla el resto del cuatrimestre, gracias
