### ISSUE TITLE
Pr.1: La función oBien hace doble PM

### ISSUE THREAD

**Issue by FrancoMarengo** [FernandoRoldan77/EstrD2023s1#34]
Siempre que se pueda resolver una función analizando un único parámetro, es mejor hacerlo así. Analizar más de un parámetro agrega complejidad y permite que sea fácil olvidar casos.

**Comment by FernandoRoldan77** [comment]
Corregido.

**Comment by FrancoMarengo** [comment]
Lo mismo: Tu función continúa haciendo doble pattern matching, es decir, estás preguntando a ambos parámetros cuál es su valor. Esto es innecesario, ya que preguntando el valor de uno de los dos parámetros (en este caso) deberíamos poder intuir cuál va a ser el valor de retorno de la función, se te ocurre alguna manera para que esto sea posible?

**Comment by FernandoRoldan77** [comment]
Ya resuelto siguiendo la recomendación brindada.

**Comment by FrancoMarengo** [comment]
Muy bien :)
