### ISSUE TITLE
Pr.2: en reversa no estás usando recursión estructural

### ISSUE THREAD

**Issue by FrancoMarengo** [FernandoRoldan77/EstrD2023s1#39]
Esta es una práctica de recursión estructural, y la idea es que las puedan hacer con recursión estructural, en aquellos casos que se pueda (como este). No hay que utilizar (++), te podrías ayudar de una subtarea definida anteriormente.

**Comment by FernandoRoldan77** [comment]
Resuelto utilizando el ejercicio 11 "agregarAlFinal" como subtarea.

**Comment by FrancoMarengo** [comment]
Perfecto
