### ISSUE TITLE
Pr.2: la función factorial está mal 

### ISSUE THREAD

**Issue by FrancoMarengo** [FernandoRoldan77/EstrD2023s1#40]
Tiene un problema en uno de los casos y siempre retorna 0, siempre hay que probar las resoluciones antes de enviar código.

**Comment by FernandoRoldan77** [comment]
Modificado agregando una condición al factorial, no me di cuenta y plantee al revés el caso base, por eso siempre daba 0.

**Comment by FrancoMarengo** [comment]
Ahora esta perfecto
