### ISSUE TITLE
Pr.2: la función contarPokemonesQueGanan está mal

### ISSUE THREAD

**Issue by FrancoMarengo** [FernandoRoldan77/EstrD2023s1#43]
Estás haciendo recursión con ambas listas de pokemon que te pasan por parámetro y esto genera un error, porque estás descartando a "pk2" en cada paso de la recursión, no lo utilizás para nada, simplemente lo descartás. Hay que pensar bien en que casos vas a hacer pattern matching y por qué.

**Comment by FernandoRoldan77** [comment]
Corregido, se cambió el caso agregando directamente la lista completa donde si se contemplal el dato Pokemon pk2.

**Comment by FrancoMarengo** [comment]
Muy bien
