### ISSUE TITLE
Pr.2: la función esMaestroPokemon está mal

### ISSUE THREAD

**Issue by FrancoMarengo** [FernandoRoldan77/EstrD2023s1#44]
Es innecesario y mala práctica definir una lista con los 3 tipos de pokemon existentes para después recorrerla y validar que estén los 3 tipos de pokemon. Esto te llevo a realizar la subtarea sonLos3Tipos que hace recursión sobre esta lista de tipos, pero que si le pasas una lista de tipos vacía da True siempre, esto esta totalmente mal. Finalmente tu código da False con varios maestros pokemon. Te facilitaría las cosas preguntar si están los 3 tipos de pokemon de otra manera y no utilizando una lista para después recorrerla.

**Comment by FernandoRoldan77** [comment]
Se corrigió toda la función siguiendo las recomendaciones, chequeando que tenga al menos un tipo de los 3 Pokémon en la función "estanTodosLosTipos".

**Comment by FrancoMarengo** [comment]
Muy bien!
