### ISSUE TITLE
Pr.2: la función mismoTipo tiene un caso mal

### ISSUE THREAD

**Issue by FrancoMarengo** [FernandoRoldan77/EstrD2023s1#45]
Para el caso en que comparas dos tipo Agua por igualdad falla, esto hace fallar a todas las funciónes que la utilizan.

**Comment by FernandoRoldan77** [comment]
Se borró la función mismo tipo y se usó  la función auxiliar sonMismosTipos(auxiliar de la práctica 1) y modificadas en las funciones aplicadas.
Una consulta, porque la que tenía mal, donde el primer caso era AGUA AGUA daba False, y la agregada "sonMismosTipos" funciona bien, es por el orden de los casos según como está armado el "data TipoDePokemon = Agua | Fuego | Planta " ? No me quedo claro eso.

**Comment by FrancoMarengo** [comment]
No, tenias un caso en el que nombrabas mal a la función y ponías "mimosTipo", era para que te fijes bien en los detalles que pueden hacer fallar el código completamente. Muy bien por reutilizar lo que ya tenias definido, si ya sabes que funciona simplemente volvé a utilizar lo que ya creaste, es buena práctica. Resuelto :)
