### ISSUE TITLE
Pr.2: tu función losDevSenior retorna casos de más

### ISSUE THREAD

**Issue by FrancoMarengo** [FernandoRoldan77/EstrD2023s1#46]
Tu función no solo cuenta a los roles "Developer" si no que también tiene en cuenta a los roles "Management" para el resultado final.

**Comment by FernandoRoldan77** [comment]
Corregida, se agregó una función "todosLosRolesSeniorsSinManagement" para que no cuente a los roles "Management"

**Comment by FrancoMarengo** [comment]
Perfecto, muy bien resuelto! :)
