### ISSUE TITLE
Pr.3: en ponerN estas perdiendo información

### ISSUE THREAD

**Issue by FrancoMarengo** [FernandoRoldan77/EstrD2023s1#49]
Pones la cantidad de bolitas pedidas, pero al llegar a 0 descartas las Celdas que te habían pasado por parámetro y retornas CeldaVacía...Además, haciendo esto tu función llega al caso base bajo la condición de que la celda que te hayan pasado por parámetro sea una CeldaVacia, de lo contrario cuelga. No probaste tu función después de resolverla, esto es muy importante

**Comment by FernandoRoldan77** [comment]
Corregido cambiando el caso base de CeldaVacia por un argumento celda.

**Comment by FrancoMarengo** [comment]
Bien
